name: "test_agent"
description: "A simple demonstration agent showcasing the basic capabilities of the 
  AgenticAI framework. Handles straightforward task routing, file
  operations, and small-scale code or document generation."

project_root: "./test_docs"

llm:
  chat:
    model: "accounts/fireworks/models/llama-v3p1-8b-instruct"
    base_url: "https://api.fireworks.ai/inference/v1"
    api_key_name: "FIREWORKS_API_KEY"
    rate_limit_seconds: 5.0

  chat_completion:
    model: "accounts/fireworks/models/llama-v3p1-8b-instruct"
    base_url: "https://api.fireworks.ai/inference/v1"
    api_key_name: "FIREWORKS_API_KEY"
    rate_limit_seconds: 5.0
    
memory:
  embedding:
    provider: "FIREWORKS"
    model: "nomic-ai/nomic-embed-text-v1"
    api_key_name: "FIREWORKS_API_KEY"
    
  vector_db:
    name: "test_agent_memory"
    backend: "chroma"
    persist_directory: "./vector_db/test_agent_memory"
    chunk_size: 2000
    chunk_overlap: 200
    retriever_k: 3


